name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # required to create the GitHub Release and upload assets

jobs:
  build-testbin:
    name: Build testbin (${{ matrix.goarch }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26.x"

      - name: Build testbin
        run: make testbin TESTBIN_GOARCH=${{ matrix.goarch }}

      - name: Rename asset
        run: mv _output/testbin _output/testbin-linux-${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: testbin-linux-${{ matrix.goarch }}
          path: _output/testbin-linux-${{ matrix.goarch }}
          if-no-files-found: error

  release:
    name: Create release
    needs: build-testbin
    runs-on: ubuntu-24.04

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: testbin-linux-*
          path: _output/
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eadb05d550f17154226a # v2.2.2
        with:
          generate_release_notes: true
          files: _output/testbin-linux-*
          fail_on_unmatched_files: true
